version: '3'

services:
  php:
    build: .
    command: php -S 0.0.0.0:90 index.php
    container_name: phpTest
    ports:
      - "90:90"
    volumes:
      - ./:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: awtor
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: your_email@example.com
      PGADMIN_DEFAULT_PASSWORD: your_password
    ports:
      - "91:80"
    depends_on:
      - postgres


